import Head from "next/head";

import { Quicksand } from "@next/font/google";
import { Header } from "components/Header/Header";

const quicksand300 = Quicksand({ subsets: ["latin"], weight: "300" });
const quicksand400 = Quicksand({ subsets: ["latin"], weight: "400" });
const quicksand500 = Quicksand({ subsets: ["latin"], weight: "500" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Felipe Moreira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:flex">
        <Header />
        <h1 className="text-white">hello</h1>
      </div>
    </>
  );
}
